<a href="https://colab.research.google.com/github/upwind1993/Numerical-Analysis/blob/main/10%EC%9E%A5/10%EC%9E%A5_LU%EB%B6%84%ED%95%B4%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python SciPy linalg의 서브 모듈로
L, U matrices와 permutation matrix, P를 생성

 		from scipy.linalg import lu
		P,L,U = lu(A)
		d = np.linalg.solve(L,b)
		x = np.linalg.solve(U,d)

import scipy as sc로 scipy 모듈 전체를 가져오고, sc.linalg.lu(A)를 사용해 lu 함수를 호출

		import scipy as sc
		P,L,U = sc.linalg.lu(A)
		d = np.linalg.solve(L,b)
		x = np.linalg.solve(U,d)


예제 10.4

In [2]:
import scipy as sc
import numpy as np
A = np.matrix(' 3 -0.1 -0.2 ; 0.1 7 -0.3 ; 0.3 -0.2 10 ')
b = np.matrix(' 7.85 ; -19.3 ; 71.4 ')
P,L,U = sc.linalg.lu(A)
d = np.linalg.solve(L,b)
x = np.linalg.solve(U,d)
print(x)

[[ 3. ]
 [-2.5]
 [ 7. ]]


예제 10.5 (파이썬을 사용한 Cholesky 분해법)

Python’s SciPy’s linalg submodule has a Cholesky function that performs the factorization: <br> <br>
		from scipy.linalg import cholesky  <br>
		U = sc.linalg.cholesky(A)


In [3]:
import numpy as np
from scipy.linalg import cholesky
A = np.matrix(' 6 15 55 ; 15 55 225 ; 55 225 979')
U = cholesky(A)
print(U)


[[ 2.44948974  6.12372436 22.45365598]
 [ 0.          4.18330013 20.91650066]
 [ 0.          0.          6.11010093]]
