<a href="https://colab.research.google.com/github/upwind1993/Numerical-Analysis/blob/main/10%EC%9E%A5/%EC%98%88%EC%A0%9C10_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

우선, Scipy와 NumPy 모듈을 불러오고, A 매트릭스와 b 벡터를 생성한다.

In [3]:
import numpy as np
from scipy.linalg import cholesky

A = np.matrix(' 6 15 55 ; 15 55 225 ; 55 225 979')
b = np.matrix( [[np.sum(A[0,:])], [np.sum(A[1,:])], [np.sum(A[2,:])] ])
print(b)


[[  76]
 [ 295]
 [1259]]


Cheolesky 분해를 수행하면 다음과 같다

In [4]:
U = cholesky(A)
print(U)

[[ 2.44948974  6.12372436 22.45365598]
 [ 0.          4.18330013 20.91650066]
 [ 0.          0.          6.11010093]]


원래의 행렬을 계산하여 이 분해가 제대로 되었는지를 확인한다.

In [5]:
Ut = U.transpose()
Atest = Ut.dot(U)
print('Atest = \n', Atest)

Atest = 
 [[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]


해를 구하기 위해서 다음의 명령어를 수행한다.

In [6]:
d = np.linalg.solve(Ut, b)
x = np.linalg.solve(U, d)
print('Solution is \n', x)


Solution is 
 [[1.]
 [1.]
 [1.]]


In [ ]:
예상된 결과가 나옴