<a href="https://colab.research.google.com/github/upwind1993/Numerical-Analysis/blob/main/11%EC%9E%A5/%EC%98%88%EC%A0%9C11_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.matrix('150. -100. 0. ; -100. 150. -50. ; 0. -50. 50. ')
Ainv = np.linalg.inv(A)
print(Ainv)

[[0.02 0.02 0.02]
 [0.02 0.03 0.03]
 [0.02 0.03 0.05]]
