<a href="https://colab.research.google.com/github/upwind1993/Numerical-Analysis/blob/main/13%EC%9E%A5/13%EC%9E%A5(%EA%B3%A0%EC%9C%A0%EC%B9%98).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

예제 13.1 행렬의 고윳값과 고유벡터

In [1]:
import numpy as np
coeff = np.array([1., -31., 175., 282., -2076.])
r = np.roots(coeff)
print('Roots are:\n',r)


Roots are:
 [23.04467254 -3.23389171  7.4501013   3.73911787]


In [40]:
import numpy as np
A = np.array([[40.,-20.,0.],[-20.,40.,-20.],[0.,-20.,40.]])
np.set_printoptions(precision=5)
print(np.linalg.eigvals(A))


[68.28427 40.      11.71573]


In [41]:
e,v = np.linalg.eig(A)
print('Eigenvalues are\n',e)
print('\nEigenvector matrix is\n',v)


Eigenvalues are
 [68.28427 40.      11.71573]

Eigenvector matrix is
 [[-5.00000e-01 -7.07107e-01  5.00000e-01]
 [ 7.07107e-01 -1.28296e-16  7.07107e-01]
 [-5.00000e-01  7.07107e-01  5.00000e-01]]


In [42]:
import numpy as np
A = np.array([[450.,-200.,0.],[-240.,420.,-180.],[0.,-225.,225.]])
e,v = np.linalg.eig(A)
print('\nEigenvalues are:\n',e)
print('\nEigenvectors are:\n',v)


Eigenvalues are:
 [698.59819 339.47789  56.92392]

Eigenvectors are:
 [[-0.58785 -0.63436  0.2913 ]
 [ 0.7307  -0.35055  0.57251]
 [-0.34714  0.68899  0.76641]]


In [47]:
wn = np.sqrt(e)/2/np.pi
print('\nResonant frequencies in Hz:\n',wn)


Resonant frequencies in Hz:
 [4.20663 2.93242 1.20079]


In [51]:
vt = np.zeros((3,3))
for i in range(3):
	    vt[:,i] = v[:,i]/v[2,i]
print('\nScaled eigenvectors are:\n',vt)


Scaled eigenvectors are:
 [[ 1.6934  -0.9207   0.38008]
 [-2.10488 -0.50879  0.747  ]
 [ 1.       1.       1.     ]]
